# Generated by Django 4.1.13 on 2024-10-18 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.JSONField(default=list)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('night_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
