# Generated by Django 4.1.13 on 2024-10-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='shifts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
